name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ok-nick/setup-aftman@v0.4.2
      - run: aftman install
      - run: lune run check
        timeout-minutes: 2
      - run: rojo build default.project.json -o build/Clases.rbxm
        timeout-minutes: 2
